Separate commands for toggling status and message buffers
atlas-engineer/nyxt pull request #2012
Opened 2022-01-11 11:02 UTC by guojing0

This is to resolve Issue https://github.com/atlas-engineer/nyxt/issues/2009 by introducing `toggle-status-buffer` and `toggle-message-buffer` commands.

2022-01-11 14:53 UTC, aartaka commented
CI breaks because removed `(un)present-current-window` is used elsewhere :)

A question to test the use-case: what if I want to make one command call to disable the status buffer? Even if it's disabled. What should I do then? That's why I suggested adding `enable-p` keyword argument to the `toggle-status-bar` in #2009: one may want to disable things unconditionally of thier current state.

2022-01-11 14:56 UTC, aartaka commented on source/window.lisp
> +      (ffi-window-set-message-buffer-height window (height (message-buffer-height window)))
What does `(height (message-buffer-height window))` returns?

2022-01-11 15:03 UTC, aartaka commented
To rephrase my chaotic questions, here's a list of distinct API actions one should have with status bar and message area:
- Enable status bar.
- Disable status bar.
- Toggle status bar.
- Enable message area.
- Disable message area.
- Toggle message area.
- Enable both.
- Disable both.
- Toggle both.

The most ergonomic way that I can think of is three commands with keyword arguments from #2009, but I may be mistaken.

2022-01-11 15:29 UTC, guojing0 commented
I vaguely remember that we may have a macro that automatically generates `enable-*`, `disable-*`, and `toggle-*` commands?

2022-01-11 15:59 UTC, aartaka commented
> I vaguely remember that we may have a macro that automatically generates `enable-*`, `disable-*`, and `toggle-*` commands?

I don't remember of such a macro, but we don't need it, actually: we only need some three commands and several helper functions.

2022-01-11 15:59 UTC, aartaka commented
The way I'd do it is close to what I suggested in #2009 :)

2022-01-12 09:38 UTC, guojing0 commented
> what if I want to make one command call to disable the status buffer? Even if it's disabled already.

Sorry I do not follow. Why would one do that?

2022-01-12 17:18 UTC, aartaka commented
> > what if I want to make one command call to disable the status buffer? Even if it's disabled already.
> 
> Sorry I do not follow. Why would one do that?

This might be useful when writing configuration snippets and to replace `(un)present-current-window`.
- Existing use-case: we need to unconditionally hide both aread when fullscreening a video and unconditionally show those when unfullscreening.
- Future use-case: one might want to have a minimum distraction mode where it unconditionally disables everything but the web page. Even if other mode have already disabled e.g. status buffer, it should still keep it disabled, instead of toggling.

> I agree with `enable-p`. To understand the desired behavior of `enable-p`, if it's set to `T`, then that area is hidden?

If set to `T`, then show; if set to `NIL`, then hide; if not provided, toggle. Actually, it might be better to name it `show-p`. What do you think?

2022-01-13 14:21 UTC, guojing0 commented
Thank you for the explanation, Artyom. It's really useful to understand better.

However, given current implementation, I do not think we need that many APIs. Say, if an user only wants to permanently disable status buffer, then he can just add something like `(toggle-status-buffer :show-p nil)` in his config file.

2022-01-14 06:27 UTC, aartaka requested changes
Looks good and comprehensive enough! There are small things that I'd like to see resolved before we merge, though :)

2022-01-14 06:27 UTC, aartaka commented on source/window.lisp
> +(define-command toggle-status-buffer (&optional (window (current-window))
SBCL complains about `&optional` and `&key` arguments being present in the same arglist. Mixing the two confuses both human readers and compilers. 

In this particular case, `&key` would work for both args.

2022-01-14 06:27 UTC, aartaka commented on source/window.lisp
> +  "Toggle the visibility of the status buffer by default.
The "by default" is not necessary here, given that you explain `show-p` later.

2022-01-14 06:27 UTC, aartaka commented on source/window.lisp
> +- If SHOW-P is T, then `status-buffer' is always enabled;
"If SHOW-P is non-nil", maybe?

Then the second clause becomes "If SHOW-P is nil...".

2022-01-14 06:27 UTC, aartaka commented on source/window.lisp
> +  (if show-provided-p
These nested `if` don't look right. How about a `cond`? Something like:
``` lisp
(cond
  ((and show-provided-p show-p)
   (enable-status-buffer window))
  ((and (not show-provided-p)
        (zerop (ffi-window-get-status-buffer-height window)))
   (enable-status-buffer window))
  (t (disable-status-buffer window)))
```

2022-01-14 06:27 UTC, aartaka commented on source/window.lisp
> +  "Toggle the visibility of the message buffer by default.
Same as above.

2022-01-14 06:28 UTC, aartaka commented
> However, given current implementation, I do not think we need that many APIs, unless I misunderstood your intention: Say, if an user only wants to permanently disable status buffer, then he can just add something like `(toggle-status-buffer :show-p nil)` in his config file.

That's exactly what I meant -- adding command behavior altering keyword arguments qualifies as API expansion :)

2022-01-14 07:39 UTC, guojing0 commented
Many thanks. In this case, do you think `(un)present-current-window` can be removed? Or, you have some suggestions for a better name, as someone whose second language is English, when I first saw this it's quite confusing.

2022-01-14 07:41 UTC, guojing0 commented on source/window.lisp
> +- If SHOW-P is T, then `status-buffer' is always enabled;
From the language perspective, "non-nil" is more correct, but would it be more clear if we "only allow" `T` and `NIL`?

2022-01-14 07:55 UTC, aartaka commented
> Many thanks. In this case, do you think `(un)present-current-window` can be removed? Or, you have some suggestions for a better name, as someone whose second language is English, when I first saw this it's quite confusing.

I was confused too :D 

Yes, I believe it can be removed. Just use the matching `toggle-message-buffer` and `toggle-status-buffer` instead in `"fullscreen"` and `"unfullscreen"` signals in `renderer/gtk.lisp`

2022-01-14 08:48 UTC, closed without merging