Issue 2185
atlas-engineer/nyxt pull request #2192
Opened 2022-04-13 13:47 UTC by aadcg

This is my suggestion to solve #2185.  However, it doesn't work!

There are some funny business going on with the `prompt-buffer` and I didn't figure it out yet.

@Ambrevar, I think you could give me a hand here.

2022-04-13 13:49 UTC, aadcg commented
```lisp
(prompt :prompt "Test prompt"
        :auto-return-p t
        :sources (list (make-instance 'prompter:source :name "Test"
                                                       :constructor '("foo" "bar"))))
```

The above behaves as expected, i.e. after narrowing down to either "foo" or "bar", the prompt vanishes. The same isn't true when it comes to the hinting mechanism.

2022-04-15 11:07 UTC, Ambrevar commented on source/mode/element-hint.lisp
> +AUTO-RETURN-P defines whether the prompt exists automatically after narrowing
Typo: "exits"

2022-04-15 11:10 UTC, Ambrevar commented
Works for me!

I tried on the `help` page then wrote `common` (for  common settings) and it got me there without pressing enter.

Can you produce a recipe?

2022-04-15 11:13 UTC, Ambrevar commented on source/mode/element-hint.lisp
> +                    &key (multi-selection-p t)
If you enable `multi-selection` by default, it means we must pass `:multi-selection nil` where it does not make sense (e.g. `follow-hint`).  

That said, is it worth the change?

2022-04-15 11:33 UTC, aartaka commented on source/mode/element-hint.lisp
> +                    &key (multi-selection-p t)
`follow-hint` is multi-selection-enabled :)

2022-04-15 11:41 UTC, aadcg commented on source/mode/element-hint.lisp
> +                    &key (multi-selection-p t)
Right @aartaka. I made this change since multi-selection seemed to be the rule, rather than the exception.

2022-04-15 15:52 UTC, aadcg commented
> Works for me!
> 
> I tried on the `help` page then wrote `common` (for common settings) and it got me there without pressing enter.
> 
> Can you produce a recipe?

Did you start Nyxt without any config? I suspect that you have set `auto-follow-hints-p` to `t`.

2022-04-15 16:00 UTC, aadcg commented on source/mode/element-hint.lisp
> +AUTO-RETURN-P defines whether the prompt exists automatically after narrowing
Good catch!

2022-04-16 07:17 UTC, aartaka commented
See this [snippet from prompter.lisp](https://github.com/atlas-engineer/nyxt/blob/7f50560c2c17284087116e042dd14666167dc161/libraries/prompter/prompter.lisp#L175): `auto-return-p` only works when there's only one suggestion left.

``` lisp
(when (and (auto-return-p prompter)
             (sera:single (all-suggestions prompter)))
    (return-selection prompter))
```

2022-04-16 08:08 UTC, Ambrevar commented on source/mode/element-hint.lisp
> +                    &key (multi-selection-p t)
Oops, looks like I read it wrong, my bad.

2022-04-16 08:09 UTC, Ambrevar commented
@aadcg No I started without any init file.

@aartaka This is correct, isn't it?

2022-04-16 08:10 UTC, aartaka commented
Yes, correct behavior it is! We just need to adjust the filters for the sources we want to make `auto-return-p`-able!

2022-04-16 08:11 UTC, aartaka commented
(Actually, if we user `auto-return-p` and reasonable custom filters, then we don't need `auto-follow-hints-p`...)

2022-04-18 06:15 UTC, Ambrevar commented
> We just need to adjust the filters for the sources we want to make `auto-return-p`-able!

What do you mean?  Are the filters problematic for link hinting?

2022-04-18 08:55 UTC, aadcg commented
I agree that `auto-follow-hints-p` (and thus `auto-follow-timer`) should be deprecated. 

However, I'm still confused about @Ambrevar's claim that this is working for him.

2022-04-18 08:59 UTC, aadcg commented
I think I understood my confusion. There's a `prompt` and a `prompter`. Let me try to fix this.

2022-04-18 20:23 UTC, aadcg commented
Ok, I understood why I said it doesn't work, while @Ambrevar says it does.  We're both right.

Let's look at simple things, shall we? Here's the bug I found:

```lisp
(prompt :prompt "Test prompt"
        :auto-return-p t
        :sources (list (make-instance 'prompter:source :name "Test"
                                                       :constructor '("fooooo" "barrrrr"))))
```

When prompted, typing "fo" suffices to narrow down to one suggestion. But the prompt doesn't exit at that time! You need to type an extra character. In fact, you can type any kind of bogus character that bears no connections with "fooooo", say "foj" or "fom".

This is especially annoying when it comes to narrowing down the hinting mechanism. Say I want to go to hint "PT", then I need to type "PT.", where "." is any character.

2022-04-19 07:01 UTC, Ambrevar commented
Excellent investigation!  Indeed, the auto-return-p logic was run in
parallel to the source update, which is wrong.  I've moved it to run
after the sources are done updating, see
94be3b8cdf726df0776d508e5803064722601d91.

Does it work for you now?

2022-04-19 09:26 UTC, aadcg commented
Thank you for looking into it @Ambrevar. 

There's something that worries me, tho. Commit 94be3b8c doesn't seem to descend from its parent. The diff looks fishy. What's going on here?

2022-04-19 09:49 UTC, Ambrevar commented
It's fine here, how are you looking at it?  `git`, magit, github?

2022-04-19 10:06 UTC, aadcg commented
It's indeed ok. My bad, sorry! I was trying to follow your solution.

2022-04-20 09:23 UTC, aartaka commented
> @aartaka, do we still need `prompter:follow-mode-functions` in `hint-source`?

Yes we do! One may wish to disable `auto-return-p` and have hints nicely highlighted when chosen!

Actually, I'd like to have this behavior be configurable. How about we resurrect `nyxt/web-mode:auto-follow-hints-p` and use it as the default value of `auto-return-p` in `query-hints`? This way ones wishing to have it instantaneous will have it, and ones (like me) wanting to utilize multiple selection and fuzzy matching will enjoy it setting the slot to nil.

2022-04-20 09:34 UTC, aartaka requested changes

2022-04-20 09:34 UTC, aartaka commented on source/mode/element-hint.lisp
> +      (sera:and-let* ((matches (string-equal
But wait, is this form even necessary now that we use `auto-return-p`? It should rather be abstracted into a separate prompt filter.

Ideas for the filter:
- If hint letters (e.g. "dx" for "DX" hint) are inputted, make the hint with these letters the sole one, triggering `auto-follow-p`.
- If there's more than three letters, fall back to `prompter:delete-inexact-matches`, or even regular fuzzy matching.
- Make it a post-process filter, so that user has some time to quickly type in more than two letters.

2022-04-20 09:34 UTC, aartaka commented on source/mode/element-hint.lisp
> +                         (auto-return-p t)
Should it be `t` by default? Don't underestimate the power of defaults...

I'd say we should allow the user to explore the power of fuzzy matching by default, while allowing to configure the `auto-return-p` easily enough for those that want it.

2022-04-20 09:34 UTC, aartaka commented on source/mode/element-hint.lisp
> +  "Like `follow-hint', but open them in new buffers (no focus)."
"them" should rather be "selected hints" so that it doesn't cofuse the reader what "them" is :)

2022-04-20 09:34 UTC, aartaka commented on source/mode/element-hint.lisp
> +  "Like `follow-hint-new-buffer', but with focus."
"but with focus" needs an expansion -- it's not clear that it opens a _new_ buffer that's _immediately focused_.

2022-04-20 09:34 UTC, aartaka commented on source/mode/element-hint.lisp
>    (query-hints "Copy element URL" (lambda (result)  (%copy-hint-url (first result)))
Should be `:multi-selection-p nil` here -- we cannot copy ten hints into clipboard all at once.

2022-04-20 09:34 UTC, aartaka commented on source/prompt-buffer.lisp
> -  :sources (list (make-instance 'prompter:source :filter #'my-suggestion-filter)))
Why this change? If you want to add an example of simple prompt, then it's better as a separate example, instead of replacing the existing one. Two different examples are better than one :)

2022-04-21 10:56 UTC, aadcg commented on source/mode/element-hint.lisp
> +                         (auto-return-p t)
Honestly, I think the defaults of the hinting mechanism are too advanced and confusing. Here's how I see it: 

- no `prompt-bufer` at all, since it hides a significant part of the hints. @Ambrevar, correct me if I'm wrong, but this seemed to be far from trivial.
- no `multi-selection-p` disabled by default. It's the most general case, but not the most frequent.
- `auto-return-p` enabled by default. 

To make it crystal clear, from an UI/UX perspective: the user triggers one of `follow-hint`, `follow-hint-new-buffer` or `follow-hint-new-buffer-focus`; the buffer gets populated by the hints (`prompt-buffer` doesn`t get in the way); the user sends the input events corresponding to a single hint (usually two characters of the latin alphabet).

2022-04-21 11:05 UTC, aadcg commented on source/mode/element-hint.lisp
> +  "Like `follow-hint', but open them in new buffers (no focus)."
Fair! See fde820fe.

2022-04-21 11:18 UTC, aadcg commented on source/mode/element-hint.lisp
>    (query-hints "Copy element URL" (lambda (result)  (%copy-hint-url (first result)))
Are you suggesting that it was formerly, i.e. before the PR, wrong?

2022-04-21 11:28 UTC, aadcg commented on source/prompt-buffer.lisp
> -  :sources (list (make-instance 'prompter:source :filter #'my-suggestion-filter)))
First of all, the example was broken since it lacked `:name`. 

Second, an example should strive to be simple and down-to-earth. The main purpose of `prompt` is to suggest objects for selection (hence I added the `constructor`).

2022-04-21 11:32 UTC, aadcg commented on source/mode/element-hint.lisp
> +  "Like `follow-hint-new-buffer', but with focus."
I disagree. The reference to the new buffer comes from `follow-hint-new-buffer`. With respect to focus, your suggestion wouldn't be exhaustive since the user can select multiple hints.

The first sentence of docstrings should be succinct, even if it sacrifices some details. Those can come below.

2022-04-21 18:09 UTC, Ambrevar commented on source/mode/element-hint.lisp
> +                         (auto-return-p t)
- The prompt-buffer is a killer feature of link hinting (that's unique to Nyxt), I say let's boast it!
- `auto-return-p` is confusing by default, I would never make it the default, only expose it as an opt-in.  Rationale: let's make Nyxt more familiar and accessible.

The UX you are proposing echoes that of other tech-user browsers like Qutebrowser.  It's fine to offer this UX, but I recommend we stick with a more visually telling interface.   Tech-savvy users can always configure Nyxt if they want to. Same argument why we have CUA bindings by default.

2022-04-21 18:09 UTC, Ambrevar commented on source/mode/element-hint.lisp
> +  (remove-element-hints))
Why remove `with-current-buffer`?  This was added because without it, `remove-element-hints` may work on the wrong buffer (link hints may have focused to  new buffer in the mean time).

2022-04-21 18:09 UTC, Ambrevar commented on source/mode/element-hint.lisp
> +  "Prompt user for element hints and open them in the current buffer."
You can even remove `user`.

2022-04-21 18:09 UTC, Ambrevar commented on source/mode/element-hint.lisp
> +  "Like `follow-hint', but open the selected hints in new nosave buffers (no
Put `nosave` between Lisp quotes so that it enables cross-referencing.

2022-04-21 18:09 UTC, Ambrevar commented on source/mode/element-hint.lisp
> +  "Prompt user for element hints and open them in a new buffer with current
Same, remove `user`.

2022-04-21 18:09 UTC, Ambrevar commented on source/mode/element-hint.lisp
> +  "Prompt user for element hints and save to clipboard."
Same, remove `user`.

2022-04-21 18:09 UTC, Ambrevar commented on source/mode/element-hint.lisp
> +  "Prompt user for element hints and bookmark them."
Same.

2022-04-21 18:09 UTC, Ambrevar commented on source/mode/element-hint.lisp
> +  "Prompt user for element hints and download them."
Same.

2022-04-21 18:09 UTC, Ambrevar commented on source/mode/element-hint.lisp
> +  "Like `follow-hint-new-buffer', but with focus."
Maybe clarify which buffer gets focused.

2022-04-22 14:19 UTC, aadcg commented on source/mode/element-hint.lisp
> -          (sleep (nyxt/web-mode:auto-follow-timer (current-mode 'web)))
The slot was deprecated, but @aartaka mentioned it might make sense to bring it back.

2022-04-22 14:20 UTC, aadcg commented on source/mode/element-hint.lisp
> +  (remove-element-hints))
Ok, I'll revert it. There was a `let` nested into `let*`, does that make sense?

2022-04-22 14:25 UTC, aadcg commented on source/mode/element-hint.lisp
> +  "Prompt user for element hints and open them in the current buffer."
See 410a6520.

2022-04-22 14:27 UTC, aadcg commented on source/mode/element-hint.lisp
> +  "Like `follow-hint', but open the selected hints in new nosave buffers (no
Done, see 0154ad47.

2022-04-22 15:57 UTC, aadcg commented on source/mode/element-hint.lisp
> +  (remove-element-hints))
See 3094d770.

2022-04-22 16:04 UTC, aadcg commented
> - The prompt-buffer is a killer feature of link hinting (that's unique to Nyxt), I say let's boast it!
> - `auto-return-p` is confusing by default, I would never make it the default, only expose it as an opt-in.  Rationale: let's make Nyxt more familiar and accessible.

It's certainly unique. But I don't see how it makes selecting one single (not _multiple_) hint easier. 
I don't follow how `auto-return-p` defaulting to `nil` makes it more familiar, given what you mentioned below.

> The UX you are proposing echoes that of other tech-user browsers like Qutebrowser.  It's fine to offer this UX, but I recommend we stick with a more visually telling interface.   Tech-savvy users can always configure Nyxt if they want to. Same argument why we have CUA bindings by default.

We have CUA because it's what most people expect. Shouldn't that apply to the hinting mechanism?

I'd be thankful if @Ambrevar, @aartaka, @jmercouris or @pdelfino would me how they use the hinting system with screenshots or a short videos/gifs.

2022-04-22 18:33 UTC, Ambrevar commented
`auto-return-p` is not used in any prompt-buffer by default, so having
it in just this one would be inconsistent behaviour.

Link-hinting as a concept is not something familiar for people coming
from popular, non-power browsers.  This is where the prompt-buffer prove
useful: to guide the users and making it obvious that they can complete
against _text_ as well.

All that said, I get your point of having a command that behaves like
link-hinting in Conkeror and friends.  Then what about having a separate
command?

2022-04-25 13:30 UTC, aartaka commented on source/mode/element-hint.lisp
>    (query-hints "Copy element URL" (lambda (result)  (%copy-hint-url (first result)))
Before the PR it used the default of `:multi-selection-p nil`. You've changed the default to `t`. You can look at other commands utilizing `:multiple-selection-p` -- you've removed the `:multiple-selection-p t` clause from those, because it's default now. However, this function was left intact -- yet it, as the one relying on the old default, should've changed its `:multi-selection-p` to `nil`.

2022-04-25 13:32 UTC, aartaka commented on source/mode/element-hint.lisp
> -          (sleep (nyxt/web-mode:auto-follow-timer (current-mode 'web)))
I meant bringing the `auto-follow-hints-p` back, as it could make a good toggle and a sane default fom `auto-return-p`. Sleep timer would be unnecessary in this scenario, as everything would be done by `prompter`.

2022-04-25 15:48 UTC, Ambrevar commented
To come back to the original intent of the pull request / issue: the main problem is that we don't see the links under the prompt buffer.  To mitigate this, two provisions that we should implement regardless of this pull request:

- Add a prompt buffer binding to toggle enlarge/shrink prompt buffer height (e.g. toggle between 1 suggestion displayed and the default).
- Add prompt buffer bindings to scroll the buffer, so that we can display the part of the buffer that's hidden.  This should work also we are at the bottom of the page.

2022-04-25 19:27 UTC, jmercouris commented
It seems I programmed them AND put them in the source at some time 🙃

2022-04-25 19:44 UTC, aartaka commented
> It seems I programmed them AND put them in the source at some time 🙃

`git blame` says it was me in d5487cb94bb28e14a0351fc168f6b8bb8cd1e409 :P

2022-04-25 19:57 UTC, jmercouris commented
I swear I wrote those commands for Kabouik!!

2022-05-02 10:00 UTC, aadcg commented on source/mode/element-hint.lisp
>    (query-hints "Copy element URL" (lambda (result)  (%copy-hint-url (first result)))
You're right. I misinterpreted the diff.

2022-05-03 09:35 UTC, aadcg commented on source/mode/element-hint.lisp
> +      (sera:and-let* ((matches (string-equal
I still don't get your suggestion regarding filters.

Please check the latest state of this PR and tell me if your concerns persist.

2022-05-03 09:40 UTC, aadcg commented on source/mode/element-hint.lisp
> +                         (auto-return-p t)
I'm not convinced, but I will abide to the current behavior.

2022-05-03 10:15 UTC, aadcg commented
> `auto-return-p` is not used in any prompt-buffer by default, so having it in just this one would be inconsistent behaviour. 

Fair, we agree.

> Link-hinting as a concept is not something familiar for people coming from popular, non-power browsers. This is where the prompt-buffer prove useful: to guide the users and making it obvious that they can complete against _text_ as well. 

The elephant in the room is that prompt-buffer is a vertical completion system that defeats the purpose of link-hinting. Scrolling (manually or automatically) or re-centering doesn't fix it. 

I've asked above, and I reiterate: is it possible to have a prompt that doesn't eagerly hide part of a buffer? How hard would it be to support both a line-based completion UX (think `icomplete`) and vertical-based? 

> All that said, I get your point of having a command that behaves like link-hinting in Conkeror and friends. Then what about having a separate command?

I don't see the need. I think it's enough to tweak some class slots.

2022-05-03 10:24 UTC, aadcg commented
> Using the no-prompt hinting without multiple selection would be totally fine for VI people, but can be totally unpredictable to everyone else.

I disagree. First of all, it's a fallacy to think that there are VI-like and Emacs-like interfaces. At most, there are slightly different approaches to keybindings in VI and Emacs (no need to expand here, you get it), though they actually agree on their goals (both are modal editors, but achieve it differently).

Think of `avy`, an Emacs package. The UX isn't either "Emacsy" or "VImsy".

2022-05-03 10:36 UTC, aadcg commented
@aartaka I appreciate the detailed way you've described your hinting workflow. I requested since I was a bit skeptical someone was actually using the interface as you've described. 

If it works for you, great! The interface is certainly complete and, to some extend, user-friendly. Still, I find that it gets in the way.

2022-05-03 16:37 UTC, aartaka commented
> > Using the no-prompt hinting without multiple selection would be totally fine for VI people, but can be totally unpredictable to everyone else.
> 
> I disagree. First of all, it's a fallacy to think that there are VI-like and Emacs-like interfaces. At most, there are slightly different approaches to keybindings in VI and Emacs (no need to expand here, you get it), though they actually agree on their goals (both are modal editors, but achieve it differently).

In the core, yes, both VI and Emacs are modal. However, there's not only [`avy`](https://github.com/abo-abo/avy) in Emacs world, there's also [helm](https://github.com/emacs-helm/helm), which is an incremental narrowing framework with a lot of text matching and verticality. It was _the_ inspiration for our `prompter`, and is a good example of what I mean by non-VI (and non-vanilla-Emacs way, if you want me to spell it out :P) way of doing things -- it's not only modal, it's textual (not in the sense of TUI, but rather in the sense of textual media) also -- and this is crucial for such a semantically rich domain as web pages, with all the text they contain. So
- Using text _and_ hints is a good universal interface. Yes, it might get in the way. But if it's configurable -- just configure it not to (which is why I suggest resurrecting `auto-follow-hints-p`)!
- Using just hints -- a good setting for those that want it and that are not necessary concerned/used to the textual side of web.

2022-05-03 16:46 UTC, aartaka commented
> The elephant in the room is that prompt-buffer is a vertical completion system that defeats the purpose of link-hinting. Scrolling (manually or automatically) or re-centering doesn't fix it.
> 
> I've asked above, and I reiterate: is it possible to have a prompt that doesn't eagerly hide part of a buffer? How hard would it be to support both a line-based completion UX (think `icomplete`) and vertical-based?

Yes. Just do `(ffi-window-set-prompt-buffer-height (nyxt:ffi-buffer-evaluate-javascript (nyxt:current-prompt-buffer) (ps:ps (ps:chain (nyxt/ps:qs "#prompt") offset-height))))` after prompt rendering.

2022-05-04 22:00 UTC, aadcg commented
@aartaka thank you for the reply and the code snippet that sets the prompt buffer height. We all agree on the topics that really matter to the PR at hand! I brought to the table some topics that clearly don't fit the moment, sorry.

I believe we're very close to merge, so let's go through what might be missing or unclear:

- I deleted the deprecated `ANNOTATE-VISIBLE-ONLY-P` since there's a new release coming soon. Is this the correct policy?
- What to do about commit 6b722af0?

Thank you!

2022-05-04 22:28 UTC, closed without merging

2022-05-04 22:32 UTC, aadcg commented
Oops... I pushed to the wrong branch! What should I do now? Thanks.

2022-05-04 23:29 UTC, jmercouris commented
Well, definitely not a force push :-D

I suggest you make a commit that reverts all the changes and submit a new pull request

2022-05-04 23:35 UTC, jmercouris commented
Never ever force push onto master!