Improve hinting UI and its user-options
atlas-engineer/nyxt pull request #2419
Opened 2022-06-27 21:32 UTC by aadcg

# Description
## Compute hints in viewport

### **Before**:
![2022-05-24_17:58:27](https://user-images.githubusercontent.com/45483512/170108548-1f8fb2d6-26e4-404f-97b8-9313de352029.png)

### **After**:
![2022-08-08_12:09:38](https://user-images.githubusercontent.com/45483512/183383158-bafb6921-8c36-4a3b-ab11-2e32041b2dc7.png)

Closes #2292 
Closes #2185 
Closes #538
Closes #536.

# Discussion

The algorithm for `element-in-view-port-p` is still rather primitive, and prone to errors. Find an example below of an element that is not visible, but marked as in viewport (hint marked as **"D"**):

![2022-08-08_11:55:57](https://user-images.githubusercontent.com/45483512/183380009-ff66acf3-337f-49ac-b729-c9934615b9ba.png)

These changes make our hints much slower, i.e. the overlay appears on the screen later (even though we were adding them for the whole document before!). I have some ideas on how to fix it.

**Question**: Should `element-in-view-port-p` be a parenscript macro? I don't think so. It's a procedure, and mostly likely one we'll need to specialize depending on the situation.

**Question**: Should we automatically (probably via hooks on input events) re-compute hints as the viewport changes? I'd say no. It's trivial from the user to cancel ans re-issue the command.

**Issue**: How to remove the scope of the hints when `show-hint-scope-p` is true?

**Issue**: JS relative to `overlapped-p`.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [x] I have pulled from master before submitting this PR
- [x] My code follows the style guidelines for Common Lisp code
  - See [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf) and [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml).
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2022-06-28 07:27 UTC, Ambrevar commented on source/prompt-buffer.lisp
> +  "Collapse PROMPT-BUFFER's suggestions."
The docstring is not very clear.  If I understand this function properly, this is meant to shrink the _height_ of the buffer to just fit the input area, right?

2022-06-28 07:27 UTC, Ambrevar commented on source/mode/hint.lisp
> +                                               (current-prompt-buffer)))
While this works, it seems a bit convoluted.  This feature is useful and could be generalized.

We currently set the height in `show-prompt-buffer`.  So maybe we could change this function and have `height` accept some values:
- a number (height in pixels)
- `:default` for `(prompt-buffer-open-height (window prompt-buffer))`
- `:fit-to-prompt` for (collapse-prompt-buffer prompt-buffer)`.

Then set up a `height` slot in the `prompt-buffer` class.

Thoughts?

2022-06-28 07:28 UTC, Ambrevar commented
It's a very welcomed feature, thanks!

Why did you list #2189 as a fixed issue?  Does not seem related :p  Mistake?

2022-06-28 18:16 UTC, aadcg commented on source/prompt-buffer.lisp
> +  "Collapse PROMPT-BUFFER's suggestions."
Yes. The correct behavior, in my opinion, would be to draw it in the echo area (below `status-buffer`). But it's not a priority I think.

2022-06-28 22:03 UTC, aadcg commented
> Why did you list #2189 as a fixed issue? Does not seem related :p Mistake?

Oh, absolutely! I'll fix it!

2022-06-28 22:05 UTC, aadcg commented
Still need to address `object-attributes`.

2022-06-29 06:34 UTC, Ambrevar commented
I'm not sure what you are asking exactly.  If what you want is prompt that matches only against the hints (and not the title, etc.), then I can think of at least 2 ways to do it:
- Specialize object-attributes against the source to only display the hints.
- Set the `filter-*` slots to match only against the hints.

2022-06-29 17:06 UTC, aadcg commented
With respect to the way it behaves, I'm happy.

2022-06-29 19:12 UTC, Ambrevar commented on source/mode/hint.lisp
> +                             (cadar (prompter:attributes suggestion))
I think you want to either get the default attribute (assuming the hint is the default) using `prompter:attributes-default`, or, if it's not the default, just get the alist value with `alex:assoc-value`.

2022-06-30 16:17 UTC, aadcg commented
Working on #2292.

2022-07-04 16:10 UTC, aadcg commented
Still working on #2292. I have implemented a new way to compute the hint strings. Each has length 2, which gives 676 with an alphabet of 26 characters. That's more than enough to hint elements in viewport, even with smaller alphabets. 

I still need to make plump and JS talk to each other properly.

2022-07-05 10:16 UTC, aartaka commented
2 character-capped hints don't feel right :(

2022-07-05 10:37 UTC, aadcg commented
> 2 character-capped hints don't feel right :(

Could you explain?

2022-07-06 07:15 UTC, jmercouris commented
I believe Artyom is saying that the algorithm to generate hints should support any arbitrary amount of hints. If we can support more than two characters, we could support an infinite amount of hints. This would of course be better.

2022-08-08 12:24 UTC, aartaka commented
Possible solution to the viewport calculation slowness: you can check&store the viewport belonging of an element when parsing it in `nyxt/dom:get-document-body-json`. That should mitigate most performance problems stemming from Lisp->C->JS->C->Lisp communication.

2022-08-11 08:59 UTC, aadcg commented
Almost ready. Will mark it as ready for review soon.

2022-08-11 09:02 UTC, aadcg commented
Renaming the branch on the remote closes the PR, sorry. I guess `add-barebones-hinting-ui` isn't a bad name for this branch.

2022-08-11 09:16 UTC, aartaka commented
¯\\\_(ツ)_/¯

2022-08-12 13:03 UTC, aadcg commented
Help me, I'm a parenscript potato.

Can someone please make the following work according to the comment? @aartaka @jmercouris 

```lisp
(define-parenscript overlapped-p (id)
  "Whether ELEMENT is hidden by another overlapping element."
  (ps:let* ((element (nyxt/ps:qs-nyxt-id document (ps:lisp id)))
            (rect (ps:chain element (get-bounding-client-rect)))
            (nearest-element (ps:chain document (element-from-point (ps:chain rect left)
                                                                    (ps:chain rect top)))))
    ;; element is overlapped iff the (ps:chain element parent-node) call returns
    ;; the following error:
    ;; TypeError: null is not an object (evaluating 'element.parentNode')
    (loop while (and nearest-element
                     (not (= nearest-element element)))
          do (ps:try (setf element (ps:chain element parent-node))
                     (:catch (error))))))
```

2022-08-12 13:24 UTC, aartaka commented
I'm not sure that errors are the best way to find out the overlapping of elements. Maybe rather compare the rectangles there?

2022-08-12 13:51 UTC, aartaka requested changes
Changelog is malformed and some magic variables are not explained. I am too curious about those to leave them as is :P

2022-08-12 13:51 UTC, aartaka commented on source/changelog.lisp
>       (:li "MINOR when we add functionality in a backwards-compatible manner.")
Seems like the changelog is severely broken, judging by the diff. Can you revert the changes/rebase over master?

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +       ;; Test it with ems
The problem of hints overlapping with elements is not the one that's solvable by their size. I suggest reverting to the previous version or using no less than `1em`. Otherwise hints are less than the text on the page, which is quite likely to be unreadable.

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +   (selection-style
How about actually merging these style slots into one, like on `lispy-search`?

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +   (hint-scope-style
Again, maybe it's better to merge all the styles into one stylesheet/slot.

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +       (when (ps:lisp (show-hint-scope-p (find-submode 'hint-mode)))
I'd say insert it no matter what. One could toggle this slot on runtime, thus enabling the behavior with no style present.

Should be solved by using a unified stylesheet, too.

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +    (dolist (element (nyxt/ps:qsa document "*[nyxt-hintable]"))
Isn't `*[whatever]` equivalent to `[whatever]`?

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +    ;; this doesn't work because parenscript doesn't support loop properly
Why is it here then?

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +      (when (nyxt/ps:element-in-view-port-p element)
What about drawing off-screen hints for those beyond-viewport folks like me?

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +  ;; does it fail if the changed elements are below the threshold?
It shouldn't.

But why not just call `update-document-model`?

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +  (setf (document-model buffer) (nyxt/dom::named-json-parse (nyxt/dom::get-document-body-json))))
Why? It should update itself once it sees how much the page has changed.

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +    (if (shrink-prompt-buffer-p (find-submode 'hint-mode))
How is prompt-buffer shrinking related to element filtering? It feels off. How about adding yet another toggle instead? We already have `auto-follow-hints-p`...

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +                                (plump:get-attribute element "nyxt-hint")
Alternative: use `plump:attribute` and fit it on one line :P

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +    (unless (shrink-prompt-buffer-p (find-submode 'hint-mode))
Why not? Can still be useful, no?

2022-08-12 13:51 UTC, aartaka commented on source/mode/hint.lisp
> +                      (selector (str:concat (str:replace-all
Wow, that feels terribly wrong... Can we somehow hide `nyxt-hintable` under the rug? -- it's a magic implementation detail, after all.

2022-08-12 13:51 UTC, aartaka commented on source/parenscript-macro.lisp
> +              (<= (chain rect top) (- (chain window inner-height) 4))
Why -4?

2022-08-12 13:51 UTC, aartaka commented on source/prompt-buffer.lisp
> +          (cond ((eq height :default)
`case`?

2022-08-12 13:51 UTC, aartaka commented on source/prompt-buffer.lisp
> +     (height
This one is useful beyond hinting, actually. How about setting it by default when `:inivisible-input-p` is T? Otherwise the password prompts are ugly... 

CC @Ambrevar?

2022-08-12 14:01 UTC, aadcg commented on source/changelog.lisp
>       (:li "MINOR when we add functionality in a backwards-compatible manner.")
What's wrong with the changelog? Did you follow the commits?

2022-08-12 14:05 UTC, aadcg commented on source/mode/hint.lisp
> +    ;; this doesn't work because parenscript doesn't support loop properly
Because I need to report the bug.

2022-08-12 14:06 UTC, aadcg commented on source/mode/hint.lisp
> +      (when (nyxt/ps:element-in-view-port-p element)
Fair enough.

2022-08-12 14:09 UTC, aadcg commented on source/parenscript-macro.lisp
> +              (<= (chain rect top) (- (chain window inner-height) 4))
I'm saying that if an element is partially visible by 4px, then fine. Why exactly 4? Trial and error.

2022-08-12 14:10 UTC, aadcg commented on source/changelog.lisp
>       (:li "MINOR when we add functionality in a backwards-compatible manner.")
Which magic variables are you referring to?

2022-08-12 14:13 UTC, aartaka commented on source/mode/hint.lisp
> +    ;; this doesn't work because parenscript doesn't support loop properly
Fair point :D

2022-08-12 14:14 UTC, aartaka commented on source/parenscript-macro.lisp
> +              (<= (chain rect top) (- (chain window inner-height) 4))
That is most probably dependent on the DPI of the scree. Maybe use something like half of the element?

And put a comment there explaining that it's for partial visibility :)

2022-08-12 14:15 UTC, aartaka commented on source/changelog.lisp
>       (:li "MINOR when we add functionality in a backwards-compatible manner.")
Magic variable of -4 for element visibility, for instance :)

2022-08-12 14:16 UTC, aartaka commented on source/changelog.lisp
>       (:li "MINOR when we add functionality in a backwards-compatible manner.")
Oh, okay, forget the changelog. Now I see that you've reordered it for clarity.

2022-08-12 19:17 UTC, aadcg commented on source/mode/hint.lisp
> +       ;; Test it with ems
I agree. How would you solve it?

2022-08-12 19:17 UTC, aadcg commented on source/mode/hint.lisp
> +   (selection-style
Agree.

2022-08-13 19:24 UTC, aadcg commented on source/mode/hint.lisp
> +    (dolist (element (nyxt/ps:qsa document "*[nyxt-hintable]"))
Indeed! It was just a reminder that I don't want `*[foo]`, but `tag1[foo], tag2[foo], ...`.

2022-08-14 19:24 UTC, aadcg commented
I'm getting a really weird warning from SBCL after commit b8cf9d222. @aartaka do you have any idea on how to fix my macro hack? If I can't come up with smth, I'll do it in the most obvious and less elegant way:

```lisp
(export-always 'define-parenscript-async)
(defmacro define-parenscript-async (script-name args &body script-body)
  "Define parenscript function SCRIPT-NAME.
SCRIPT-BODY must be a valid parenscript and will be wrapped in (PS:PS ...).
Any Lisp expression must be wrapped in (PS:LISP ...).

The returned function sends the compiled Javascript to the current buffer webview.
The function can be passed ARGS."
  `(defun ,script-name ,args
     (ffi-buffer-evaluate-javascript-async (current-buffer)
                                           (ps:ps ,@script-body))))
```

> 
> failed AVER: (NULL SB-C::CURRENT)
> This is probably a bug in SBCL itself. (Alternatively, SBCL
> might have been corrupted by bad user code, e.g. by an undefined
> Lisp operation like (FMAKUNBOUND 'COMPILE), or by stray pointers
> from alien code or from unsafe Lisp code; or there might be a
> bug in the OS or hardware that SBCL is running on.) If it seems
> to be a bug in SBCL itself, the maintainers would like to know
> about it. Bug reports are welcome on the SBCL mailing lists,
> which you can find at <http://sbcl.sourceforge.net/>.
>    [Condition of type SB-INT:BUG]
>

2022-08-14 20:01 UTC, aadcg commented
I'll resume this on Tuesday.

2022-08-14 20:05 UTC, aadcg commented
> Help me, I'm a parenscript potato.
> 
> Can someone please make the following work according to the comment? @aartaka @jmercouris
> 
> ```lisp
> (define-parenscript overlapped-p (id)
>   "Whether ELEMENT is hidden by another overlapping element."
>   (ps:let* ((element (nyxt/ps:qs-nyxt-id document (ps:lisp id)))
>             (rect (ps:chain element (get-bounding-client-rect)))
>             (nearest-element (ps:chain document (element-from-point (ps:chain rect left)
>                                                                     (ps:chain rect top)))))
>     ;; element is overlapped iff the (ps:chain element parent-node) call returns
>     ;; the following error:
>     ;; TypeError: null is not an object (evaluating 'element.parentNode')
>     (loop while (and nearest-element
>                      (not (= nearest-element element)))
>           do (ps:try (setf element (ps:chain element parent-node))
>                      (:catch (error))))))
> ```

To answer my own question, a simply way of going around is:

```
(define-parenscript overlapped-p (id)
  "Whether ELEMENT is hidden by another overlapping element."
  (ps:let* ((element (nyxt/ps:qs-nyxt-id document (ps:lisp id)))
            (rect (ps:chain element (get-bounding-client-rect)))
            (nearest-element (ps:chain document (element-from-point (ps:chain rect left)
                                                                    (ps:chain rect top)))))
    (loop while (and nearest-element
                     element
                     (not (= nearest-element element)))
          do (setf element (ps:chain element parent-node)))
    (null element)))
```

2022-08-16 19:08 UTC, aadcg commented on source/mode/hint.lisp
> +    ;; this doesn't work because parenscript doesn't support loop properly
[Reported](https://gitlab.common-lisp.net/parenscript/parenscript/-/issues/10).

2022-08-17 07:53 UTC, aadcg commented on source/mode/hint.lisp
> +  ;; does it fail if the changed elements are below the threshold?
Because `update-document-model` adds the nyxt identifiers, but those get there when the page is loaded in the first place. I just want to update the `document-model` slot.

Actually my comment about changed elements shows a misunderstanding of mine.

2022-08-17 08:32 UTC, aadcg commented on source/mode/hint.lisp
> +  (setf (document-model buffer) (nyxt/dom::named-json-parse (nyxt/dom::get-document-body-json))))
It seems it doesn't, according to my tests...

2022-08-17 10:05 UTC, aadcg commented on source/mode/hint.lisp
> +    (if (shrink-prompt-buffer-p (find-submode 'hint-mode))
I agree that prompt-buffer shrinking is unrelated to element filtering.

But it feels odd to add another toggle. How about setting the filter according to `auto-follow-hints-p`?

2022-08-17 10:14 UTC, aadcg commented on source/mode/hint.lisp
> +                                (plump:get-attribute element "nyxt-hint")
Good call.

2022-08-17 10:15 UTC, aadcg commented on source/mode/hint.lisp
> +    (unless (shrink-prompt-buffer-p (find-submode 'hint-mode))
When the prompt-buffer is reduced to the input area there's no selection (thus no highlighting).

2022-08-17 10:18 UTC, aadcg commented on source/mode/hint.lisp
> +                      (selector (str:concat (str:replace-all
Yes, it's terrible. 

Is this worth it though? How big is the performance penalty between selecting `[nyxt-hintable]` and `hints-selector` such that they have the `nyxt-hintable` attribute?

2022-08-17 10:39 UTC, aadcg commented on source/parenscript-macro.lisp
> +              (<= (chain rect top) (- (chain window inner-height) 4))
> That is most probably dependent on the DPI of the screen.

I don't think so. Each element has a box that is measured in pixels, and that is absolute as soon as it gets rendered in whatever combination of hardware and output device (monitor).

> Maybe use something like half of the element?

That would fail the purpose. A partially visible element is still visible. To achieve that, we any to subtract any non zero integer to `inner-height/width`. I don't see how could that value be conditional. We can set it to 1, for the time being.

2022-08-17 10:47 UTC, aadcg commented on source/prompt-buffer.lisp
> +          (cond ((eq height :default)
Good call.

2022-08-17 10:56 UTC, aadcg commented on source/mode/hint.lisp
> +    (if (shrink-prompt-buffer-p (find-submode 'hint-mode))
> How about setting the filter according to auto-follow-hints-p?

My above suggestion is a bad one.

2022-08-17 12:35 UTC, aartaka commented on source/mode/hint.lisp
> +  ;; does it fail if the changed elements are below the threshold?
But what's the problem of adding identifiers?

2022-08-17 12:38 UTC, aartaka commented on source/mode/hint.lisp
> +    (unless (shrink-prompt-buffer-p (find-submode 'hint-mode))
But wait, the underlying prompter still has a selection, even though it's not shown as listing of suggestions. I'm suggesting to highlight the selected hint for the combination of `auto-return-p nil` and `shrink-prompt-buffer t`.

2022-08-17 12:40 UTC, aartaka commented on source/mode/hint.lisp
> +                      (selector (str:concat (str:replace-all
Performance is not my concern here, I'm worried about the fact that one can redefine the `hint-selector` to something like `a | button | img` and it will go wrong in a terrible way. You shall not change the user-configurable selector in any way, because there might be _anything_ there.

2022-08-17 13:03 UTC, aartaka commented
@aadcg, see 1db1e33d180e02e783c82534a8c4614c4ea46ae0 for the `:buffer` and `:async` argument to `peval`.

2022-08-17 17:41 UTC, aartaka commented
Same for `pflet` in c1ce1c1f6eeca4328f4dd517ac784e5a6353de5e!

2022-08-18 09:34 UTC, aadcg commented
@aartaka, I find the implementation a bit odd. Keyword arguments aren't positional, but we force them to be. It feels wrong to me.

Also, let's not forget about #2227.

2022-08-18 11:58 UTC, aartaka commented
> @aartaka, I find the implementation a bit odd. Keyword arguments aren't positional, but we force them to be. It feels wrong to me.

Still, it's better of a pattern than any other I thought of:
- Putting async and buffer before the bindigns list in `pflet`.
- Adding another mandatory arglist (that's what StumpWM, `defclass`, and some libraries do).

While this one resembles the pattern of method qualifiers that occupy an arbitrary space after the method name and before the args. So, it's still more or less CL-ish, just a bit special :)

Also note that there's no syntax (except addditional arglist) for this particular problem that would be supported by `destructuring-bind`. We have to stretch the parsing anyway, so why not make the most comfy version of the syntax we could have?

> Also, let's not forget about #2227.

Ah, I should probably close that. Thanks for mentioning!

2022-08-18 15:08 UTC, aadcg commented on source/prompt-buffer.lisp
> +     (height
Is it possible to set a slot based on the value of another slot?

2022-08-18 16:42 UTC, aartaka commented on source/prompt-buffer.lisp
> +     (height
No. The best shot here would be to check `invisible-input-p` in `intialize-instance :after` or `customize-instance :after` or somewhere else it's reliably set.

2022-08-18 17:53 UTC, aadcg commented on source/mode/hint.lisp
> +    (unless (shrink-prompt-buffer-p (find-submode 'hint-mode))
You're correct, but there's a catch to it. That holds as longs as filtering is set to

```lisp
(lambda (suggestion source input)
          (declare (ignore source))
          (str:starts-with-p input
                             (prompter:attributes-default suggestion)
                             :ignore-case t))
```

In other words, if the filtering only cares about the hint strings.

2022-08-18 17:56 UTC, aadcg commented on source/mode/hint.lisp
> +                      (selector (str:concat (str:replace-all
I've rewritten this bit, so this doesn't matter anymore.

But I don't see how would that be the case. I was setting the selector for `add-hints` by manipulating the `hints-selector` slot, not by mutating it.

2022-08-18 18:08 UTC, aadcg commented
> Also note that there's no syntax (except addditional arglist) for this particular problem that would be supported by destructuring-bind. We have to stretch the parsing anyway, so why not make the most comfy version of the syntax we could have?

I didn't follow you here.

2022-08-18 18:15 UTC, aadcg commented on source/prompt-buffer.lisp
> +     (height
Could you test 8f836f6d9, since I don't use `password-mode`?

2022-08-18 18:57 UTC, aadcg commented
We should merge this in my opinion.

Some things like `prompter:filter` and `prompter:selection-actions` might be a bit polemical, but I still think it's the best we can do now.

2022-08-19 06:32 UTC, Ambrevar commented
Why re-order the changelog?  Any benefit?  I prefer adding the the bottom, it creates less noise in diffs.

Re-ordering also mostly breaks the history for the whole file: is it worth it?

2022-08-19 06:33 UTC, Ambrevar commented
@aartaka requested a change.

2022-08-19 08:48 UTC, aadcg commented
> Why re-order the changelog? Any benefit? I prefer adding the the bottom, it creates less noise in diffs.

It seems odd that we need to go to the bottom of a file to add an entry to the changelog. Regarding diffs, I don't see the difference it makes. Example?

Notice that the changelog was broken with regards to the order:

```
     30:(define-version "2.0.0"
     67:(define-version "2.1.0"
    104:(define-version "2.1.1"
    116:(define-version "2.2.0"
    209:(define-version "2.2.1"
    239:(define-version "2.2.2"
    258:(define-version "2.2.3"
    291:(define-version "2.2.4"
    331:(define-version "3-pre-release-1"
    440:(define-version "3.0.0"
```

If the order of old-to-new would be respected then `3-pre-release-1` would come last.

> Re-ordering also mostly breaks the history for the whole file: is it worth it?

That is not entirely true. You can still follow the history and `git blame`, it just takes an extra step. But it's a fair point.

Still, if I revert this commit, I'll move `3-pre-release-1` to the very bottom.

2022-08-19 08:54 UTC, aadcg commented
I don't understand how can I mark as resolved the changes that @aartaka requested, without dismissing his review. Can we use less GitHub paraphernalia? It gets in the way.

2022-08-19 12:04 UTC, aartaka commented
Ahhhh.

2022-08-19 12:04 UTC, aartaka approved these changes

2022-08-19 12:07 UTC, aartaka commented
I feel like lost and not remembering anything about the recent changes in this PR, but one thing I'm sure: changelog is better off staying as it is, because files naturally grown downwards, not upwards (why tho?) :D

2022-08-19 12:09 UTC, Ambrevar commented
> If the order of old-to-new would be respected then `3-pre-release-1` would come last.

Artyom did this.  In any case, the pre-release entries can disappear from the final 3.0.0 changelog I think.

2022-08-19 12:16 UTC, aartaka commented
> > If the order of old-to-new would be respected then `3-pre-release-1` would come last.

I don't understand the logic of this statement. 3.0.0 comes after 3-pre-release-1 (chronologically), so why say that 3-pre-release-1 comes after 3.0.0?

> Artyom did this. In any case, the pre-release entries can disappear from the final 3.0.0 changelog I think.

Yes, they won't be there in 3.0.0, but it's nice to keep track of separate releases while we're doing them!

2022-08-19 12:18 UTC, aadcg commented
> I feel like lost and not remembering anything about the recent changes in this PR, but one thing I'm sure: changelog is better off staying as it is, because files naturally grown downwards, not upwards (why tho?) :D

Files don't naturally grow downwards. That's a psychological barrier we inherited from writing on paper.

I've never seem a changelog that keep old entries at the top, as it makes hardly any sense. See, for instance, [Emacs changelogs](https://git.savannah.gnu.org/cgit/emacs.git/tree/ChangeLog.1), and the change log major mode Emacs provides `(info "(emacs) Change Log")`.

2022-08-19 12:27 UTC, aadcg commented
> I don't understand the logic of this statement. 3.0.0 comes after 3-pre-release-1 (chronologically), so why say that 3-pre-release-1 comes after 3.0.0?

Correct. I should have said that it makes little sense to have a changelog section corresponding to a release tag that doesn't exist!

2022-08-19 12:29 UTC, aartaka commented
Does it not exist? 0_o

2022-08-19 12:29 UTC, aartaka commented
Are we lying to ourselves about the existence of 3-pre-release-1? I don't know what to believe anymore...

2022-08-19 12:31 UTC, aadcg commented
> Yes, they won't be there in 3.0.0, but it's nice to keep track of separate releases while we're doing them!

Agree. Any tagged release should have a corresponding changelog section, which I think we consistently do.

2022-08-19 12:32 UTC, aadcg commented
>  Are we lying to ourselves about the existence of 3-pre-release-1? I don't know what to believe anymore...

I'm not sure what you're expressing here. 

I was suggesting that commit d4cf43539 might not have been a good move, a view that @Ambrevar seems to share.

2022-08-19 12:45 UTC, aadcg commented on source/mode/hint.lisp
> +   (shrink-prompt-buffer-p
Thanks for pointing out!

2022-08-19 12:45 UTC, aadcg commented on source/mode/hint.lisp
> +    (if (ps:lisp (compute-hints-in-view-port-p (find-submode 'hint-mode)))
Indeed!

2022-08-19 12:48 UTC, aadcg commented on source/mode/hint.lisp
> +  (defun create-hint-overlay (original-element hint)
Are you sure this is good call, given that it uses [Document.createElement()](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement)?

2022-08-19 12:49 UTC, aadcg commented on source/mode/hint.lisp
> +      ((zerop length) (error "Length must be greater than 0"))
Agree! I was looking for smth like `alex:positive-integer`, thanks for pointing it out!

2022-08-19 12:57 UTC, aadcg commented on source/mode/hint.lisp
> +      ((= 1 (length alphabet))
Ok, why not!

2022-08-19 12:59 UTC, aadcg commented on source/mode/hint.lisp
> +   (compute-hints-in-view-port-p
> Is this set anywhere? How do we use it? Is it meant to be exported?

It's a user option. I'm not sure if I'm following you...

>  As for show-hint-scope-p, we may need an example here.

Indeed. I'll try to come up with a good example by means of writing, since a visual one would be ideal.

2022-08-19 13:07 UTC, Ambrevar commented
I mean it's not a very big deal, it's just changelog.  Let's adopt a workflow and stick to it :)

2022-08-19 14:09 UTC, aartaka commented on source/mode/hint.lisp
> +                      (selector (str:concat (str:replace-all
You weren't mutating, but you were building something on top of it having assumptions on its contents (namely, that it's a comma-separated list of selectors). But no assumption is true about its contents, except that it's some CSS selector (which is arguable too).

2022-08-19 14:25 UTC, aartaka commented on source/mode/hint.lisp
> +        (ps:dolist (element elements)
Note that you repeat `ps:dolist` twice here. Maybe put `if` inside `ps:dolist` then?

2022-08-19 14:25 UTC, aartaka commented on source/mode/hint.lisp
> +  (setf (document-model buffer) (nyxt/dom::named-json-parse (nyxt/dom::get-document-body-json)))
Still, this is too resemblant of `update-document-model`. Is the performance penalty of indexing more elements in `update-document-model` that scary, actually?

2022-08-19 14:25 UTC, aartaka commented on source/mode/hint.lisp
> +  (setf (document-model buffer) (nyxt/dom::named-json-parse (nyxt/dom::get-document-body-json))))
Again, `update-document-model` won't hurt.

2022-08-19 14:25 UTC, aartaka commented on source/mode/hint.lisp
> +    (if (fit-to-prompt-p (find-submode 'hint-mode))
Maybe move the check inside the filter and check `auto-return-p` of the `(current-prompt-buffer)`? That would be quirky, but more semantically sound :thinking:

2022-08-19 14:25 UTC, aartaka commented on source/mode/hint.lisp
> +                         (selector "[nyxt-hintable]"))
Why leave it as argument if it's an implementation detail now?

2022-08-19 14:25 UTC, aartaka commented on source/mode/hint.lisp
> +    (query-hints "Open element"
But wait, `follow-hint` does not necessarily open things. Does it open buttons? Does it open `<details>` or `<select>`s? Well, the latter two, maybe, but not the buttons. "Go to element" is not exactly fitting of an action either, though. Maybe "Interact with an element" or something akin to it?

2022-08-19 14:46 UTC, aadcg commented on source/mode/hint.lisp
> +    (query-hints "Open element"
Good call.

2022-08-19 14:54 UTC, aadcg commented on source/mode/hint.lisp
> +                         (selector "[nyxt-hintable]"))
I finally understand your point, and you're right.

But what I realized just now is that this is a huge problem, since the calls to `query-hints` that pass the `selector` keyword argument will not behave as intended.

2022-08-19 14:56 UTC, aadcg commented on source/mode/hint.lisp
> +  (setf (document-model buffer) (nyxt/dom::named-json-parse (nyxt/dom::get-document-body-json))))
Can a point a situation where it's necessary?

2022-08-19 15:22 UTC, aadcg commented on source/mode/hint.lisp
> +                      (selector (str:concat (str:replace-all
That is true... Not sure how to proceed here. [Especially after this observation](https://github.com/atlas-engineer/nyxt/pull/2419#discussion_r950281810).

2022-08-19 15:39 UTC, aadcg commented on source/mode/hint.lisp
> +                      (selector (str:concat (str:replace-all
Actually it's trivial to fix this. See the latest iteration.

2022-08-19 17:13 UTC, aadcg commented on source/mode/hint.lisp
> +        (ps:dolist (element elements)
If you mean that I could write it as:

```lisp
(define-parenscript set-hintable-attribute (selector)
  (let ((elements (nyxt/ps:qsa document (ps:lisp selector))))
    (ps:dolist (element elements)
      (if (ps:lisp (compute-hints-in-view-port-p (find-submode 'hint-mode)))
          (when (nyxt/ps:element-in-view-port-p element)
            (ps:chain element (set-attribute "nyxt-hintable" "")))
          (ps:chain element (set-attribute "nyxt-hintable" ""))))))
```

Yes, I could but I would be evaluating `(ps:lisp (compute-hints-in-view-port-p (find-submode 'hint-mode)))` countless time for nothing.

2022-08-19 17:24 UTC, aadcg commented on source/mode/hint.lisp
> +        (ps:dolist (element elements)
I was trying to avoid some calls, but it's probably not worth it.

2022-08-20 12:22 UTC, aartaka commented on source/mode/hint.lisp
> +        (ps:dolist (element elements)
But then, you're not avoiding any, because the value of `compute-hints-in-view-port-p` is baked into the JavaScript the moment you start running it...

2022-08-22 07:13 UTC, aadcg commented on source/mode/hint.lisp
> +    (if (fit-to-prompt-p (find-submode 'hint-mode))
Is 9fb57f80d what you had in mind?

2022-08-22 07:24 UTC, aadcg commented on source/mode/hint.lisp
> +   (compute-hints-in-view-port-p
Does 16258e072 look better?

2022-08-22 07:53 UTC, aadcg commented on source/mode/hint.lisp
> +    (if (fit-to-prompt-p (find-submode 'hint-mode))
It doesn't work to call `current-prompt-buffer` in the filter. Most likely because the filter is called when the prompt buffer is open? 

I think aea167a9e will make you happy.

2022-08-22 07:58 UTC, aadcg commented
Ready to merge from my side.

2022-08-22 08:15 UTC, aartaka commented on source/mode/hint.lisp
> +    (if (fit-to-prompt-p (find-submode 'hint-mode))
Yep, aea167a should be enough :)

2022-08-22 08:25 UTC, aartaka commented
I'd expand the changelog with the value of each addition, like
```
Add nyxt/hint-mode:fit-to-prompt-p to configure whether the prompt takes the bare minimum of the screen space or not.
Add nyxt/hint-mode:show-hint-scope-p for Konkeror-style element highlighting.
Add height so that every prompt can have a configurable height.
```

But then, `:nxref` kinda shows it to those curious enough. The question is: do we want `:nxref` in changelog? Or are we better off with the plain HTML changelog that can be shown in any browser?
- Staying with plain HTML means we can publish the changelog right away on atlas.engineer. But it makes us think more on what to put in the text, like in my example above.
- Using `:nxref` (and other niceties from Nyxt) makes changelog nicer to use inside Nyxt, but quirky to host at atlas.engineer.

Trade-offs...

To not prolong the review of this PR, I suggest using plain `:code` tags for now. I'll open an issue about this.

2022-08-23 11:00 UTC, aadcg commented
All addressed @aartaka. I just left the word "Konkeror" out of the changelog.

Ok to merge?

2022-08-23 11:19 UTC, aartaka commented
@aadcg, yes!

2022-08-23 11:50 UTC, aadcg commented
Ok! Notice that the tests failed due to [this commit](https://github.com/atlas-engineer/nyxt/commit/38906b3e960c7c531fa90f27c53ee570040bfe1b#commitcomment-81930387).

2022-08-23 11:54 UTC, aartaka commented
Nope, tests fail because of d63d692e624ccbde92333d726a785ab8a455b79d :P

And 4c868b3990771866c7dae0fea30fd6d8c84d94aa fixes it on master ;)

2022-08-23 11:55 UTC, aadcg commented
Merged via a0f9f77ae.

2022-08-23 11:55 UTC, closed without merging