Add toggle-maximize command
atlas-engineer/nyxt pull request #2475
Opened 2022-07-22 14:09 UTC by maggiplant

# Description

This pull request adds the command toggle-maximize, which maximizes the current Nyxt window analogous to how toggle-fullscreen makes the current Nyxt window occupy the entire screen. This allows a user to maximize a Nyxt window from the REPL, in config.lisp/init.lisp or from the "Execute Command" prompt.

On the QTWebEngine side, this requires exposing widgetShowMaximized for which I have filed a pull request here: https://github.com/atlas-engineer/cl-webengine/pull/14

This feature is tested as working in nyxt/gi-gtk (cloned from master just before I made the first commit in this pull request). Unfortunately, I have not been able to test it in nyxt/qt, since I could not get cffi to load libwebengine.so (or its alternatives) on Guix System (I could not find anything that provides `libQt5WebEngineWidgets.so.5.15.2` in my `guix environment`).

Fixes #2474

# Discussion

I have copied `ffi-window-unfullscreen` as `ffi-window-unmaximize` in qt.lisp. This is to keep things symmetrical with GTK which has a seperate `window-unmaximize` function as opposed to QT which has only `widget-show-normal`.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [X] I have pulled from master before submitting this PR
- [X] There are no merge conflicts.
- [X] I've added the new dependencies as:
  - [X] ASDF dependencies,
  - [X] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [X] and Guix dependencies.
- [X] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [X] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [X] Documentation:
  - [X] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [X] I have updated the existing documentation to match my changes.
  - [X] I have commented my code in hard-to-understand areas.
  - [X] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [X] I have added a `migration.lisp` entry for all compatibility-breaking changes.
- [ ] Compilation and tests:
  - [X] My changes generate no new warnings.
  - [ ] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [ ] New and existing unit tests pass locally with my changes.

2022-07-24 09:09 UTC, aartaka requested changes
Thanks for this! Some changes are due, but it looks good in general :)

2022-07-24 09:09 UTC, aartaka commented on source/renderer/gtk.lisp
> +	 (connect-signal window "window-state-event" nil (widget event)
Note that it's better to add one handler per signal, so your code here better belong to the fullscreen-setting handler above.

2022-07-24 09:09 UTC, aartaka commented on source/renderer/qt.lisp
> +(defmethod ffi-window-maximize ((window qt-window))
QT port is abandoned, but no hurt in adding those, I suppose :shrug:

2022-07-24 09:09 UTC, aartaka commented on source/window.lisp
> +	(ffi-window-unmaximize window)
The indentation seems to be off...

2022-07-24 09:09 UTC, aartaka commented on source/window.lisp
> +  (toggle-status-buffer :show-p (not maximized))
Why toggle status and message area when (un-)maximizing? Seems to be unrelated, no?

2022-07-24 18:57 UTC, maggiplant commented on source/renderer/gtk.lisp
> +	 (connect-signal window "window-state-event" nil (widget event)
Fixed!

2022-07-24 18:58 UTC, maggiplant commented on source/renderer/qt.lisp
> +(defmethod ffi-window-maximize ((window qt-window))
Ah, I was not aware of this

2022-07-24 19:00 UTC, maggiplant commented on source/window.lisp
> +	(ffi-window-unmaximize window)
Do you mean the unncessary calls to `toggle-status-buffer` and `toggle-message-buffer`? Otherwise it seems fine to me (and to `M-x indent-region`)

2022-07-24 19:02 UTC, maggiplant commented on source/window.lisp
> +  (toggle-status-buffer :show-p (not maximized))
Right, these were to my careless copying of `toggle-fullsceen`😅

2022-07-25 07:33 UTC, aartaka commented on source/window.lisp
> +	(ffi-window-unmaximize window)
I mean that the conventional indentation for Common Lisp is that all the three clauses of an `if` expression have the same offset. Note that Common Lisp and Emacs Lisp are quite different in regards to indentation, so plain `indent-region` won't help much, unless you run SLIME/SLY in the background.

If installing SLIME or SLY for the sake of re-indenting the code is too much hustle for you, I can do that after merging :)

2022-07-25 11:10 UTC, maggiplant commented on source/window.lisp
> +	(ffi-window-unmaximize window)
It looks like that is the case now. I usually have Sly running in the background. Explicitly opening Sly on window.lisp and trying to indent the expression with `M-x indent-region` and pressing `TAB` on every line seems to yield the same indentation as it currently has.

Am I missing something? 🙃

2022-07-25 12:06 UTC, aartaka commented on source/window.lisp
> +	(ffi-window-unmaximize window)
I'm not sure. It definitely looks off, but if SLY doesn't help, then I don't know what do do 0_o

I'll merge and re-indent as a separate commit. Thanks for this PR @maggiplant!

2022-07-25 12:06 UTC, merged

2022-07-25 17:25 UTC, maggiplant commented on source/window.lisp
> +	(ffi-window-unmaximize window)
Thanks for reviewing it!