Document modes and subsystems
atlas-engineer/nyxt pull request #2957
Opened 2023-05-10 17:23 UTC by aartaka

# Description

This documents lots of modes as an attempt to document everything for #2303 (with minor indentation and function signature fixes I was unable to resist). @Ambrevar, @aadcg, you can push your documentation improvements to this branch, if you want to.

**Manual testing and bugfixes don't belong to this PR, it's about documentation exclusively. Push to master or open separate PRs for that.**

# Discussion

## Documentation formats
It the course of documenting things, I've kind of settled at a certain structure for package and mode documentation. Packages are for implementation details and APIs, modes are for commands, configuration, and other user-facing things. That's why their documentation is interlinked, but different. Here's what I've arrived at:

### Package 
```
Package for `...-mode', mode for [description].

Implementation details (functions, macros, classes, sources etc.):
- [...]
- [...]
[...]

See the `...-mode' for the external user-facing APIs.
```

## #Mode
```
[Concise and plain language description of the mode]
[Additional details about it]

Commands:
[...]

Configuration options:
[...]

See `nyxt/mode/...' package documentation for implementation details and internal programming APIs.
```

Obviously, these formats are merely a recommendation, because every mode is unique. But still, would be nice to have a certain consistency and structure. So @Ambrevar, @aadcg, try using these formats and feel free to suggest better ones for us to have!

## Responsibility distribution

@Ambrevar, can I take care of `repeat-mode`, `editor-mode`, and `cruise-control-mode` documentation now that they're broken/underdocumented?

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [X] Git hygiene:
  - I have pulled from master before submitting this PR
  - There are no merge conflicts.
- [X] I've added the new dependencies as:
  - ASDF dependencies,
  - Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - and Guix dependencies.
- [X] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [X] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [X] Documentation:
  - All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - I have updated the existing documentation to match my changes.
  - I have commented my code in hard-to-understand areas.
  - I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [X] Compilation and tests:
  - My changes generate no new warnings.
  - I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - I ran the tests locally (`(asdf:test-system :nyxt)` and `(asdf:test-system :nyxt/gi-gtk)`) and they pass.

2023-05-10 20:02 UTC, aadcg commented
I'm reviewing this PR tomorrow, first thing in the morning. Thanks!

2023-05-11 07:34 UTC, aadcg commented
With respect to the documentation format, any format is better than no format! By the principle of "monkey see, monkey do", future modes will follow that structure and that's positive indeed.

Remark: the discussion of the WHAT belong to Issues, not PRs. In PRs, you discuss the HOW. As you can imagine, no one will be unreasonable to the point of starting a discussion about the doc structure since, in the end, it could trigger re-doing a big portion of your work. In short, you're presenting us to that format post factum. 

---- 

I'll be pushing commits to this PR. You can revert them later as you please.

2023-05-11 07:51 UTC, Ambrevar commented
> @Ambrevar, can I take care of `repeat-mode`, `editor-mode`, and `cruise-control-mode` documentation now that they're broken/underdocumented?

Please do :)

2023-05-11 08:54 UTC, Ambrevar commented
I'm actually not too much in favour of command and option listing: they are cumbersome to maintain and risk running out of sync.

After all, package documentations should provide the user with the list of commands.  Same for class documentation and the slots.

2023-05-11 09:10 UTC, aadcg commented
> I'm actually not too much in favour of command and option listing: they are cumbersome to maintain and risk running out of sync.

> After all, package documentations should provide the user with the list of commands. Same for class documentation and the slots.

That's exactly what I wanted to say, but [settled on a more polite observation](https://github.com/atlas-engineer/nyxt/pull/2957#issuecomment-1543484235).

We have `describe-mode`, and I think that's where we should fit the keybindings and user options (mode slots).

2023-05-11 09:18 UTC, aadcg commented on source/mode/history.lisp
> +  (:documentation "Mode to persist navigation into the global history and navigate around it.
Try to put yourself in the shoes of a newcomer. A mode that persists navigation and enabling navigating in this thing called "global history". Hmm... 

Now let's look at the old version.

> Mode to store current buffer navigation into the global history.

Well, I can actually imagine what it does!

2023-05-11 09:24 UTC, aadcg commented on source/mode/keyscheme.lisp
> +`nyxt/mode/emacs'/`keymaps:emacs', is enabled."))
Honestly, it was much better as it was. I don't understand the meaning of:

> Ensures that a single keybindings mode, such as `nyxt/mode/emacs'/`keymaps:emacs', is enabled.

But I think it means "Ensures that a single keyscheme is enables", which is already clear from "All modes that set `keyscheme' should inherit from this mode.".

2023-05-11 09:25 UTC, aadcg commented on source/mode/keyscheme.lisp
> +`nyxt/mode/emacs'/`keymaps:emacs', is enabled.
Same.

2023-05-11 09:31 UTC, aadcg commented on source/mode/no-procrastinate.lisp
> +;;; poorly written, rotting in the dark.
This comment  begs the question "is the effort put in documenting the mode worth it"?

I will not review this commit.

2023-05-11 09:39 UTC, aadcg requested changes
@aartaka I've left some comments in the PR's diff, sent some commits and made some general observations.

@Ambrevar's observation about the documentation structure makes sense to me.

2023-05-11 09:47 UTC, aartaka commented on source/mode/no-procrastinate.lisp
> +;;; poorly written, rotting in the dark.
It kinda isn't worth it, yes. But still, for completeness sake...

2023-05-11 09:53 UTC, aartaka commented on source/mode/keyscheme.lisp
> +`nyxt/mode/emacs'/`keymaps:emacs', is enabled."))
Done in 5cc8709e37ed8fc035c397cdb22647593f21f1bd!

2023-05-11 09:55 UTC, aartaka commented on source/mode/history.lisp
> +  (:documentation "Mode to persist navigation into the global history and navigate around it.
Reverting in cb6916944c9c90cf740a226776a8cefd51002494 ೖ(⑅σ̑ᴗσ̑)ೖ

2023-05-11 10:03 UTC, aartaka commented
Indeed, @Ambrevar, you're correct. Especially given that mode `describe-*` page now lists all the commands belonging to the mode （；¬＿¬)

Command listings in mode docs are removed in 23ceaac64969d9d35dc65ce03c0738baf505772d (but I've retained package documentation with internals, because it's useful for hacking on said packages.)

2023-05-11 10:12 UTC, aadcg commented on source/mode/repeat.lisp
> +  "Create a command dispatcher that counts the M-digic keys and adds them together.
I missed a typo here! "digit" instead of "digic".

2023-05-11 10:16 UTC, aadcg approved these changes

2023-05-11 10:16 UTC, aadcg commented
Sure! I forgot about it. 

I agree about squashing it all down to a single commit.

2023-05-11 10:23 UTC, merged

2023-05-11 10:23 UTC, aartaka commented
Pushed with bd709c9c21aa4c4c944bbade427d775d02160294!

2023-05-11 10:24 UTC, aadcg commented
Thanks!

2023-05-11 10:27 UTC, aartaka commented
@aadcg, there are several modes that you're to document, if you don't mind (I've chaotically documented modes from `annotate` to `cruise-control', sorry):
```
document
download
emacs
expedition
file-manager
force-https
```

And then @Ambrevar:
```
process
prompt-buffer
proxy
reading-line
record-input-field
reduce-bandwidth
reduce-tracking
remembrance
repeat
repl
search-buffer
small-web
spell-check
style
tts
user-script
vi
visual
watch
```